version: '3'

services:
  web:
    image: wl_gel2mdt_web
    build:
      context: .
    command: bash -c ". /root/gel2mdt/Docker/startup_script.sh && cd /root/gel2mdt/gelweb && python manage.py runserver 0.0.0.0:8003"
    ports:
      - "8003:8003"
    stdin_open: true
    tty: true
    env_file:
      - /etc/gel2mdt/credentials_wl
    volumes:
      - .:/root/gel2mdt/
      - /home/bioadmin/.vep/:/root/.vep
      - /home/bioadmin/graham/wl_gel2mdt_resources:/root/gel2mdt_cache
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wl_gel2mdt_db
      - MYSQL_USER=paddy
    env_file:
      - /etc/gel2mdt/credentials_wl
    volumes:
      - /home/bioadmin/graham/wl_gel2mdt_resources/gel2mdt_db:/var/lib/mysql
  jupyter:
    image: wl_gel2mdt_jupyter
    build: .
    restart: always
    build:
      context: .
    command: bash -c ". /root/gel2mdt/Docker/startup_script.sh && jupyter notebook --generate-config -y && cd /root/gel2mdt/gelweb && python manage.py shell_plus --notebook"
    volumes:
      - .:/root/gel2mdt/
      - /home/bioadmin/graham/wl_gel2mdt_resources:/root/gel2mdt_cache
    env_file:
      - /etc/gel2mdt/credentials_wl
    ports:
      - "8893:8888"
    depends_on:
      - db
      - web
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    volumes:
      - /sessions
    ports:
      - 8083:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db


#  db:
#    image: postgres:10
#    restart: always
#    environment:
#      - POSTGRES_DB=gel2mdt_db
#      - POSTGRES_USER=paddy
#    env_file:
#      - /etc/gel2mdt/credentials
#    volumes:
#      - ~/gel2mdt_resources/gel2mdt_db:/var/lib/postgresql/data


